// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BenchmarkModel(arg1) {
  return window['go']['core']['App']['BenchmarkModel'](arg1);
}

export function BrowseLlamaCppDir() {
  return window['go']['core']['App']['BrowseLlamaCppDir']();
}

export function BrowseLlamaCppDownloadDir() {
  return window['go']['core']['App']['BrowseLlamaCppDownloadDir']();
}

export function BrowseModelDownloadDir() {
  return window['go']['core']['App']['BrowseModelDownloadDir']();
}

export function BrowseModelsDir() {
  return window['go']['core']['App']['BrowseModelsDir']();
}

export function CancelDownloadTask(arg1) {
  return window['go']['core']['App']['CancelDownloadTask'](arg1);
}

export function CheckForUpdate() {
  return window['go']['core']['App']['CheckForUpdate']();
}

export function GetAppVersion() {
  return window['go']['core']['App']['GetAppVersion']();
}

export function GetCPU() {
  return window['go']['core']['App']['GetCPU']();
}

export function GetCUDA() {
  return window['go']['core']['App']['GetCUDA']();
}

export function GetConfig() {
  return window['go']['core']['App']['GetConfig']();
}

export function GetDisk() {
  return window['go']['core']['App']['GetDisk']();
}

export function GetDownloadSource() {
  return window['go']['core']['App']['GetDownloadSource']();
}

export function GetDownloadTasks() {
  return window['go']['core']['App']['GetDownloadTasks']();
}

export function GetGPU() {
  return window['go']['core']['App']['GetGPU']();
}

export function GetLlamaCpp() {
  return window['go']['core']['App']['GetLlamaCpp']();
}

export function GetLlamaCppDownloadStatus() {
  return window['go']['core']['App']['GetLlamaCppDownloadStatus']();
}

export function GetLoadedModels() {
  return window['go']['core']['App']['GetLoadedModels']();
}

export function GetMemory() {
  return window['go']['core']['App']['GetMemory']();
}

export function GetModelConfig(arg1) {
  return window['go']['core']['App']['GetModelConfig'](arg1);
}

export function GetModelDescription(arg1) {
  return window['go']['core']['App']['GetModelDescription'](arg1);
}

export function GetModelFiles(arg1) {
  return window['go']['core']['App']['GetModelFiles'](arg1);
}

export function GetModelMaxFileSize(arg1) {
  return window['go']['core']['App']['GetModelMaxFileSize'](arg1);
}

export function GetModels() {
  return window['go']['core']['App']['GetModels']();
}

export function GetMonitorStatus() {
  return window['go']['core']['App']['GetMonitorStatus']();
}

export function GetOS() {
  return window['go']['core']['App']['GetOS']();
}

export function GetServerConfig() {
  return window['go']['core']['App']['GetServerConfig']();
}

export function GetServerLogsSince(arg1) {
  return window['go']['core']['App']['GetServerLogsSince'](arg1);
}

export function GetServerStatus() {
  return window['go']['core']['App']['GetServerStatus']();
}

export function GetSystemInfo() {
  return window['go']['core']['App']['GetSystemInfo']();
}

export function GetUpdateDownloadStatus() {
  return window['go']['core']['App']['GetUpdateDownloadStatus']();
}

export function InstallUpdate() {
  return window['go']['core']['App']['InstallUpdate']();
}

export function PauseDownloadTask(arg1) {
  return window['go']['core']['App']['PauseDownloadTask'](arg1);
}

export function PauseLlamaCppDownload() {
  return window['go']['core']['App']['PauseLlamaCppDownload']();
}

export function RefreshModels() {
  return window['go']['core']['App']['RefreshModels']();
}

export function ResumeDownloadTask(arg1) {
  return window['go']['core']['App']['ResumeDownloadTask'](arg1);
}

export function ResumeLlamaCppDownload() {
  return window['go']['core']['App']['ResumeLlamaCppDownload']();
}

export function RetryDownloadTask(arg1) {
  return window['go']['core']['App']['RetryDownloadTask'](arg1);
}

export function SaveModelConfig(arg1, arg2) {
  return window['go']['core']['App']['SaveModelConfig'](arg1, arg2);
}

export function SaveServerConfig(arg1) {
  return window['go']['core']['App']['SaveServerConfig'](arg1);
}

export function SearchDownloads(arg1, arg2) {
  return window['go']['core']['App']['SearchDownloads'](arg1, arg2);
}

export function SetApiRouteMode(arg1) {
  return window['go']['core']['App']['SetApiRouteMode'](arg1);
}

export function SetDownloadSource(arg1) {
  return window['go']['core']['App']['SetDownloadSource'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['core']['App']['SetLanguage'](arg1);
}

export function SetLlamaCppDownloadDir(arg1) {
  return window['go']['core']['App']['SetLlamaCppDownloadDir'](arg1);
}

export function SetModelDownloadDir(arg1) {
  return window['go']['core']['App']['SetModelDownloadDir'](arg1);
}

export function SetModelsDir(arg1) {
  return window['go']['core']['App']['SetModelsDir'](arg1);
}

export function SetOnboardingDismissed(arg1) {
  return window['go']['core']['App']['SetOnboardingDismissed'](arg1);
}

export function SetSidebarCollapsed(arg1) {
  return window['go']['core']['App']['SetSidebarCollapsed'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['core']['App']['SetTheme'](arg1);
}

export function SetTrayEnabled(arg1) {
  return window['go']['core']['App']['SetTrayEnabled'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['core']['App']['Shutdown'](arg1);
}

export function StartDownload(arg1, arg2) {
  return window['go']['core']['App']['StartDownload'](arg1, arg2);
}

export function StartLlamaCppDownload() {
  return window['go']['core']['App']['StartLlamaCppDownload']();
}

export function StartServer() {
  return window['go']['core']['App']['StartServer']();
}

export function StartUpdateDownload(arg1) {
  return window['go']['core']['App']['StartUpdateDownload'](arg1);
}

export function Startup(arg1) {
  return window['go']['core']['App']['Startup'](arg1);
}

export function StopLlamaCppDownload() {
  return window['go']['core']['App']['StopLlamaCppDownload']();
}

export function StopServer() {
  return window['go']['core']['App']['StopServer']();
}

export function StopUpdateDownload() {
  return window['go']['core']['App']['StopUpdateDownload']();
}

export function TuneModelConfig(arg1) {
  return window['go']['core']['App']['TuneModelConfig'](arg1);
}

export function UnloadModel(arg1) {
  return window['go']['core']['App']['UnloadModel'](arg1);
}
