// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseLlamaCppDir() {
  return window['go']['core']['App']['BrowseLlamaCppDir']();
}

export function BrowseModelsDir() {
  return window['go']['core']['App']['BrowseModelsDir']();
}

export function CancelDownloadTask(arg1) {
  return window['go']['core']['App']['CancelDownloadTask'](arg1);
}

export function CheckForUpdate() {
  return window['go']['core']['App']['CheckForUpdate']();
}

export function GetAppVersion() {
  return window['go']['core']['App']['GetAppVersion']();
}

export function GetCPU() {
  return window['go']['core']['App']['GetCPU']();
}

export function GetCUDA() {
  return window['go']['core']['App']['GetCUDA']();
}

export function GetConfig() {
  return window['go']['core']['App']['GetConfig']();
}

export function GetDownloadTasks() {
  return window['go']['core']['App']['GetDownloadTasks']();
}

export function GetGPU() {
  return window['go']['core']['App']['GetGPU']();
}

export function GetLlamaCpp() {
  return window['go']['core']['App']['GetLlamaCpp']();
}

export function GetLlamaCppDownloadStatus() {
  return window['go']['core']['App']['GetLlamaCppDownloadStatus']();
}

export function GetMemory() {
  return window['go']['core']['App']['GetMemory']();
}

export function GetModelConfig(arg1) {
  return window['go']['core']['App']['GetModelConfig'](arg1);
}

export function GetModelDescription(arg1) {
  return window['go']['core']['App']['GetModelDescription'](arg1);
}

export function GetModelFiles(arg1) {
  return window['go']['core']['App']['GetModelFiles'](arg1);
}

export function GetModelMaxFileSize(arg1) {
  return window['go']['core']['App']['GetModelMaxFileSize'](arg1);
}

export function GetModels() {
  return window['go']['core']['App']['GetModels']();
}

export function GetOS() {
  return window['go']['core']['App']['GetOS']();
}

export function GetServerConfig() {
  return window['go']['core']['App']['GetServerConfig']();
}

export function GetServerStatus() {
  return window['go']['core']['App']['GetServerStatus']();
}

export function GetSystemInfo() {
  return window['go']['core']['App']['GetSystemInfo']();
}

export function GetUpdateDownloadStatus() {
  return window['go']['core']['App']['GetUpdateDownloadStatus']();
}

export function PauseDownloadTask(arg1) {
  return window['go']['core']['App']['PauseDownloadTask'](arg1);
}

export function PauseLlamaCppDownload() {
  return window['go']['core']['App']['PauseLlamaCppDownload']();
}

export function RefreshModels() {
  return window['go']['core']['App']['RefreshModels']();
}

export function ResumeDownloadTask(arg1) {
  return window['go']['core']['App']['ResumeDownloadTask'](arg1);
}

export function ResumeLlamaCppDownload() {
  return window['go']['core']['App']['ResumeLlamaCppDownload']();
}

export function RetryDownloadTask(arg1) {
  return window['go']['core']['App']['RetryDownloadTask'](arg1);
}

export function SaveModelConfig(arg1, arg2) {
  return window['go']['core']['App']['SaveModelConfig'](arg1, arg2);
}

export function SaveServerConfig(arg1) {
  return window['go']['core']['App']['SaveServerConfig'](arg1);
}

export function SearchDownloads(arg1, arg2) {
  return window['go']['core']['App']['SearchDownloads'](arg1, arg2);
}

export function SetModelsDir(arg1) {
  return window['go']['core']['App']['SetModelsDir'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['core']['App']['SetTheme'](arg1);
}

export function StartDownload(arg1, arg2) {
  return window['go']['core']['App']['StartDownload'](arg1, arg2);
}

export function StartLlamaCppDownload() {
  return window['go']['core']['App']['StartLlamaCppDownload']();
}

export function StartServer() {
  return window['go']['core']['App']['StartServer']();
}

export function StartUpdateDownload(arg1) {
  return window['go']['core']['App']['StartUpdateDownload'](arg1);
}

export function StopLlamaCppDownload() {
  return window['go']['core']['App']['StopLlamaCppDownload']();
}

export function StopServer() {
  return window['go']['core']['App']['StopServer']();
}

export function StopUpdateDownload() {
  return window['go']['core']['App']['StopUpdateDownload']();
}
