// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {context} from '../models';

export function BrowseLlamaCppDir():Promise<string>;

export function BrowseLlamaCppDownloadDir():Promise<string>;

export function BrowseModelDownloadDir():Promise<string>;

export function BrowseModelsDir():Promise<string>;

export function CancelDownloadTask(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<core.UpdateCheckResult>;

export function GetAppVersion():Promise<string>;

export function GetCPU():Promise<core.CPUInfo>;

export function GetCUDA():Promise<core.CUDAInfo>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDownloadSource():Promise<string>;

export function GetDownloadTasks():Promise<Array<core.DlTask>>;

export function GetGPU():Promise<Array<core.GPUInfo>>;

export function GetLlamaCpp():Promise<core.LlamaCppInfo>;

export function GetLlamaCppDownloadStatus():Promise<core.DownloadState>;

export function GetLoadedModels():Promise<Array<core.LoadedModel>>;

export function GetMemory():Promise<core.MemoryInfo>;

export function GetModelConfig(arg1:string):Promise<core.ModelConfig>;

export function GetModelDescription(arg1:string):Promise<string>;

export function GetModelFiles(arg1:string):Promise<Array<core.HFFileOut>>;

export function GetModelMaxFileSize(arg1:string):Promise<number>;

export function GetModels():Promise<Array<core.ModelInfo>>;

export function GetMonitorStatus():Promise<core.MonitorStatus>;

export function GetOS():Promise<Record<string, string>>;

export function GetServerConfig():Promise<core.ServerConfig>;

export function GetServerStatus():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<core.SystemInfo>;

export function GetUpdateDownloadStatus():Promise<core.UpdateDownloadState>;

export function InstallUpdate():Promise<void>;

export function PauseDownloadTask(arg1:string):Promise<void>;

export function PauseLlamaCppDownload():Promise<void>;

export function RefreshModels():Promise<Array<core.ModelInfo>>;

export function ResumeDownloadTask(arg1:string):Promise<void>;

export function ResumeLlamaCppDownload():Promise<void>;

export function RetryDownloadTask(arg1:string):Promise<void>;

export function SaveModelConfig(arg1:string,arg2:core.ModelConfig):Promise<void>;

export function SaveServerConfig(arg1:core.ServerConfig):Promise<void>;

export function SearchDownloads(arg1:string,arg2:string):Promise<Array<core.HFSearchResult>>;

export function SetApiRouteMode(arg1:boolean):Promise<void>;

export function SetDownloadSource(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<string>;

export function SetLlamaCppDownloadDir(arg1:string):Promise<void>;

export function SetModelDownloadDir(arg1:string):Promise<void>;

export function SetModelsDir(arg1:string):Promise<void>;

export function SetSidebarCollapsed(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetTrayEnabled(arg1:boolean):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartDownload(arg1:string,arg2:Array<string>):Promise<void>;

export function StartLlamaCppDownload():Promise<void>;

export function StartServer():Promise<void>;

export function StartUpdateDownload(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopLlamaCppDownload():Promise<void>;

export function StopServer():Promise<void>;

export function StopUpdateDownload():Promise<void>;

export function UnloadModel(arg1:string):Promise<void>;
