/**
 * Fake @wailsio/runtime for the pure-frontend mock preview (dev only).
 *
 * vite.config.ts swaps this module in for "@wailsio/runtime" ONLY when Vite
 * runs with `--mode mock` (npm run dev:mock). In every other mode the real
 * runtime package is used and this file is never part of the build graph.
 *
 * Surface coverage (grep-verified against every "@wailsio/runtime" import in
 * src/ and frontend/bindings/):
 *   - bindings/.../core/app.ts       → Call.ByID, CancellablePromise (type), Create
 *   - bindings/.../core/models.ts    → Create
 *   - src/App.vue                    → Application (Quit), Window (Minimise /
 *                                      ToggleMaximise / IsMaximised / Hide)
 *   - src/lib/linkHandler.ts, src/views/Docs.vue → Browser.OpenURL
 *
 * Call.ByID dispatches through the numeric method-ID table (extracted from the
 * generated app.ts) to the handler table in mockData.ts. Unknown IDs and
 * unknown method names are logged AND rejected — a missing mock must be
 * visible, never silently swallowed.
 */

import { handlers, mockServerPort, mockServerRunning, mockLoadedModels, mockAddServerLog, mockChatReply } from './mockData'

// ─── CancellablePromise ──────────────────────────────────────────────────────

/**
 * Stand-in for the runtime's CancellablePromise. The generated bindings only
 * use it as a return TYPE, so at runtime a plain promise subclass with a no-op
 * cancel() is enough.
 */
export class CancellablePromise<T = unknown> extends Promise<T> {
  oncancelled: (() => void) | null = null
  cancel(): void {
    // Nothing in flight to cancel in the mock; no-op.
  }
}

// ─── Call dispatch ───────────────────────────────────────────────────────────

// Numeric method-ID → bare method name. Extracted from
// bindings/github.com/CodeNeow/llama-cpp-desktop/core/app.ts ($Call.ByID(…)
// calls, generated by `wails3 generate bindings`). If bindings are ever
// regenerated with new methods, extend this table (unknown IDs reject loudly).
const methodIds: Record<number, string> = {
  1960463204: 'BenchmarkModel',
  3350014259: 'BrowseLlamaCppDir',
  2305276219: 'BrowseLlamaCppDownloadDir',
  1383777610: 'BrowseModelDownloadDir',
  3452550715: 'BrowseModelsDir',
  1195596959: 'CancelDownloadTask',
  2837150318: 'CheckForUpdate',
  323973705: 'GetAppVersion',
  2051216158: 'GetCPU',
  3549453655: 'GetCUDA',
  955128306: 'GetConfig',
  3567524009: 'GetDisk',
  779669993: 'GetDownloadSource',
  471464974: 'GetDownloadTasks',
  3317380266: 'GetGPU',
  1558827786: 'GetLlamaCpp',
  2430553188: 'GetLlamaCppDownloadStatus',
  2052539751: 'GetLoadedModels',
  3935674743: 'GetMemory',
  3379369827: 'GetModelConfig',
  2953385413: 'GetModelDescription',
  3059698428: 'GetModelFiles',
  3502311522: 'GetModelMaxFileSize',
  3623107510: 'GetModels',
  1406400820: 'GetMonitorStatus',
  1828890902: 'GetOS',
  2670577276: 'GetRemoteDoc',
  922492437: 'GetServerConfig',
  2272125646: 'GetServerLogsSince',
  2805866625: 'GetServerStatus',
  1207510045: 'GetSystemInfo',
  1961990283: 'GetUpdateDownloadStatus',
  2348643066: 'InstallUpdate',
  2431111255: 'PauseDownloadTask',
  2029097948: 'PauseLlamaCppDownload',
  879778009: 'RefreshModels',
  1327992246: 'ResumeDownloadTask',
  3234250677: 'ResumeLlamaCppDownload',
  1684922999: 'RetryDownloadTask',
  2454186708: 'SaveModelConfig',
  2386255100: 'SaveServerConfig',
  3752716797: 'SearchDownloads',
  1452625074: 'SetApiRouteMode',
  2913750285: 'SetDownloadSource',
  605496818: 'SetLanguage',
  1234016213: 'SetLlamaCppDownloadDir',
  714764088: 'SetModelDownloadDir',
  1326214329: 'SetModelsDir',
  799206670: 'SetOnboardingDismissed',
  4236638085: 'SetSidebarCollapsed',
  1709326749: 'SetTheme',
  3214759057: 'SetTrayEnabled',
  2707618076: 'StartDownload',
  2611530074: 'StartLlamaCppDownload',
  4115957591: 'StartServer',
  1420164860: 'StartServerWithModel',
  2696931657: 'StartUpdateDownload',
  1564418742: 'StopLlamaCppDownload',
  3351777243: 'StopServer',
  1678582909: 'StopUpdateDownload',
  769524497: 'TuneModelConfig',
  2623847304: 'UnloadModel',
}

function callByName(name: string, args: any[]): Promise<any> {
  const handler = handlers[name]
  if (!handler) {
    console.warn('[mockRuntime] no mock handler for binding method "' + name + '"')
    return Promise.reject(new Error('[mockRuntime] unmocked binding method: ' + name))
  }
  return Promise.resolve()
    .then(() => handler(...args))
    .catch((err: unknown) => {
      // Surface handler failures in the console too (e.g. validation rejects).
      console.warn('[mockRuntime] binding "' + name + '" rejected:', err)
      throw err
    })
}

function unmocked(kind: string, key: unknown): Promise<never> {
  console.warn('[mockRuntime] unknown ' + kind, key)
  return Promise.reject(new Error('[mockRuntime] unknown ' + kind + ': ' + String(key)))
}

/**
 * Mirror of the runtime's `Call` namespace shape
 * ({ Call, ByID, ByName, RuntimeError }): the generated bindings use
 * `$Call.ByID(<id>, ...args)`, ByName/Call are kept for completeness.
 */
export const Call = {
  ByID(methodID: number, ...args: any[]): Promise<any> {
    const name = methodIds[methodID]
    if (!name) return unmocked('binding method id', methodID)
    return callByName(name, args)
  },
  ByName(methodName: string, ...args: any[]): Promise<any> {
    return callByName(methodName, args)
  },
  Call(options: { methodName?: string; methodID?: number; args?: any[] }): Promise<any> {
    if (typeof options?.methodName === 'string') return callByName(options.methodName, options.args ?? [])
    if (typeof options?.methodID === 'number') return Call.ByID(options.methodID, ...(options.args ?? []))
    return unmocked('Call options', options)
  },
  RuntimeError: class MockRuntimeError extends Error {},
}

// ─── Create (type-coercion helpers used by the generated bindings) ──────────

// The mock handlers already return plain JSON-shaped data, so every coercion
// is a pass-through (arrays still map their elements through the given
// creator, matching the real semantics for nested binding classes).
const passthrough = (source: any) => source

export const Create = {
  Any: passthrough,
  ByteSlice: passthrough,
  Array: (element: (s: any) => any) => (source: any) => (Array.isArray(source) ? source.map(element) : source),
  Map: () => passthrough,
  Nullable: (element: (s: any) => any) => (source: any) => (source == null ? source : element(source)),
  Struct: () => passthrough,
  DateFromTime: passthrough,
}

// ─── Application / Window / Browser ──────────────────────────────────────────

export const Application = {
  Hide: () => Promise.resolve(),
  Show: () => Promise.resolve(),
  Quit: () => Promise.resolve(),
}

export const Window = {
  Minimise: () => Promise.resolve(),
  ToggleMaximise: () => Promise.resolve(),
  Maximise: () => Promise.resolve(),
  Unmaximise: () => Promise.resolve(),
  IsMaximised: () => Promise.resolve(false),
  IsMinimised: () => Promise.resolve(false),
  Hide: () => Promise.resolve(),
  Show: () => Promise.resolve(),
  Close: () => Promise.resolve(),
  SetTitle: (_title: string) => Promise.resolve(),
  Center: () => Promise.resolve(),
}

export const Browser = {
  OpenURL: (_url: string | URL) => Promise.resolve(),
}

// ─── fetch interception (chat page talks to llama-server directly) ──────────

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

const json = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  })

/** OpenAI-compatible SSE stream with a visibly paced typing effect. */
function chatCompletionResponse(): Response {
  const encoder = new TextEncoder()
  const reply = mockChatReply()
  // 2-character slices ≈ one CJK token per chunk, 30ms apart.
  const pieces: string[] = []
  for (let i = 0; i < reply.length; i += 2) pieces.push(reply.slice(i, i + 2))
  const body = new ReadableStream<Uint8Array>({
    async start(controller) {
      for (const piece of pieces) {
        await sleep(30)
        controller.enqueue(
          encoder.encode('data: ' + JSON.stringify({ choices: [{ delta: { content: piece } }] }) + '\n\n'),
        )
      }
      controller.enqueue(encoder.encode('data: [DONE]\n\n'))
      controller.close()
    },
  })
  return new Response(body, { status: 200, headers: { 'Content-Type': 'text/event-stream' } })
}

/** Router/OpenAI model list shared with the GetLoadedModels mock state. */
function modelsResponse(directModeFallback: boolean): Response {
  const data = mockLoadedModels().map((m) =>
    directModeFallback
      ? { id: m.id, object: 'model' }
      : { id: m.id, object: 'model', status: { value: m.status } },
  )
  return json({ object: 'list', data })
}

async function handleMockServerRequest(url: URL, init: RequestInit | undefined): Promise<Response> {
  const path = url.pathname
  const method = (init?.method ?? 'GET').toUpperCase()
  // Direct-mode fallback shape (src/lib/chat.ts): every served model is loaded.
  if (method === 'GET' && path === '/models') {
    return mockServerRunning() ? modelsResponse(false) : json({ error: { message: 'llama-server is not running (mock)' } }, 503)
  }
  if (method === 'GET' && path === '/v1/models') {
    return mockServerRunning() ? modelsResponse(true) : json({ error: { message: 'llama-server is not running (mock)' } }, 503)
  }
  if (method === 'POST' && path === '/v1/chat/completions') {
    if (!mockServerRunning()) {
      return json({ error: { message: 'llama-server is not running (mock)' } }, 503)
    }
    mockAddServerLog('srv  update_slots: all slots are busy')
    return chatCompletionResponse()
  }
  if (method === 'POST' && path === '/models/unload') {
    mockAddServerLog('[INFO] router: model unload request accepted (mock)')
    return json({ ok: true })
  }
  return json({ error: { message: 'mock llama-server has no route for ' + method + ' ' + path } }, 404)
}

// Install once per page: requests aimed at the mock llama-server
// (127.0.0.1:<mockServerPort()>) are answered locally, everything else goes to
// the real network untouched.
const fetchMarker = '__llamaMockFetchInstalled' as const
if (!(globalThis as any)[fetchMarker]) {
  ;(globalThis as any)[fetchMarker] = true
  const originalFetch = globalThis.fetch.bind(globalThis)
  globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    let url: URL | null = null
    try {
      url = new URL(typeof input === 'string' ? input : input instanceof URL ? input.href : input.url)
    } catch {
      url = null
    }
    if (url && url.hostname === '127.0.0.1' && url.port === String(mockServerPort())) {
      return handleMockServerRequest(url, init)
    }
    return originalFetch(input, init)
  }
}
