/**
 * Wails v3 bridge — wraps the statically generated bindings for the bound
 * core.App service (frontend/bindings/github.com/CodeNeow/llama-cpp-desktop,
 * regenerated by `wails3 generate bindings` whenever bound methods change).
 * Each exported wrapper keeps the exact signature and return-value shape it
 * had in the v2 window.go bridge era, so frontend consumers and the vitest
 * suites (which mock this module) stay unchanged. The `core` namespace comes
 * from the Go package core/ that hosts the App struct.
 */

import type { MonitorStatus } from './lib/monitor'
import type { ServerLogEntry } from './lib/serverLog'

import * as bindings from '../bindings/github.com/CodeNeow/llama-cpp-desktop/core/app'

// The generated bindings are statically imported, so unlike the v2
// window.go bridge there is no runtime availability probe: standalone
// (vite dev only) the calls fail at fetch time instead of throwing here.

function app(): any {
  // Untyped on purpose: the wrappers below declare their own precise return
  // types, keeping call sites and mocks byte-compatible with the v2 era.
  return bindings
}

// ─── Config ─────────────────────────────────────────────────────

export async function getConfig(): Promise<{ theme: string; llamaCppDir: string; modelsDir: string; llamaCppDownloadDir?: string; modelDownloadDir?: string; downloadSource: string; language: string; resolvedLanguage: 'zh' | 'en'; trayEnabled: boolean; apiRouteMode?: boolean; sidebarCollapsed?: boolean; onboardingDismissed?: boolean }> {
  return app().GetConfig()
}

export async function setTheme(theme: string): Promise<void> {
  return app().SetTheme(theme)
}

// Set the sidebar collapsed/expanded preference (pure UI state, no window-related side effects)
export async function setSidebarCollapsed(collapsed: boolean): Promise<void> {
  return app().SetSidebarCollapsed(collapsed)
}

// Dismiss the Home page quick-start checklist ("Don't show again" or auto-completed):
// pure UI preference persisted via the backend config's onboardingDismissed field.
export async function setOnboardingDismissed(dismissed: boolean): Promise<void> {
  return app().SetOnboardingDismissed(dismissed)
}

// Set the Windows system tray toggle (settings item rendered on Windows only; on other
// platforms the backend just persists without starting/stopping anything). systray cannot
// be started twice in one process: once disabled it stays disabled until the app restarts.
export async function setTrayEnabled(enabled: boolean): Promise<void> {
  return app().SetTrayEnabled(enabled)
}

// Toggle API-route (headless) mode (settings item rendered on Windows only). Enabling
// persists the preference, hands the running llama-server over, relaunches the app in
// headless mode (tray + llama-server only, no GUI/WebView2) and quits — the service
// keeps serving the OpenAI API without interruption. From headless, the tray "Show Main
// Window" item returns to GUI mode. On success this call never resolves visibly in the
// GUI (the app quits); failures reject for inline error display.
export async function setApiRouteMode(enabled: boolean): Promise<void> {
  return app().SetApiRouteMode(enabled)
}

// Set the UI language preference ("zh" | "en" | "auto"); the backend returns the effective
// resolvedLanguage (zh/en; auto is resolved from system detection), which store uses to
// refresh the UI copy
export async function setLanguage(language: string): Promise<string> {
  return app().SetLanguage(language)
}

// ─── System Info ─────────────────────────────────────────────────

export async function getSystemInfo(): Promise<any> {
  return app().GetSystemInfo()
}

export async function getCPU(): Promise<any> {
  return app().GetCPU()
}

export async function getMemory(): Promise<any> {
  return app().GetMemory()
}

export async function getGPU(): Promise<any> {
  return app().GetGPU()
}

export async function getCUDA(): Promise<any> {
  return app().GetCUDA()
}

export async function getLlamaCpp(): Promise<any> {
  return app().GetLlamaCpp()
}

export async function getOS(): Promise<{ os: string; arch: string }> {
  return app().GetOS()
}

// SafeArea mirrors the backend core.SafeArea: system-bar insets in physical
// pixels (Android only — status-bar/cutout band on top, gesture/nav bar on
// the bottom; all zeros elsewhere, where CSS env(safe-area-inset-*) already
// covers window chrome). Consumed by lib/safeArea.ts.
export interface SafeArea {
  top: number
  bottom: number
  left: number
  right: number
}

// getSafeArea reads the current Android system-bar insets; callers treat
// failure as soft (lib/safeArea.ts catches and keeps the env() layer alone).
export async function getSafeArea(): Promise<SafeArea> {
  return app().GetSafeArea()
}

export async function getDisk(): Promise<{ path: string; used: number; total: number } | null> {
  return app().GetDisk()
}

// ─── Monitor ─────────────────────────────────────────────────────

// Real-time monitoring (CPU / memory / GPU / inference prompt processing and generation
// decode speed); return shape matches MonitorStatus in lib/monitor.ts
export async function getMonitorStatus(): Promise<MonitorStatus> {
  return app().GetMonitorStatus()
}

// ─── Models ──────────────────────────────────────────────────────

export async function getModels(): Promise<any[]> {
  return app().GetModels()
}

export async function refreshModels(): Promise<any[]> {
  return app().RefreshModels()
}

export async function getModelConfig(modelID: string): Promise<any> {
  return app().GetModelConfig(modelID)
}

export async function saveModelConfig(modelID: string, config: any): Promise<void> {
  return app().SaveModelConfig(modelID, config)
}

// Auto-tune the model's inference parameters: the backend reads the model's GGUF
// metrics, snapshots GPU/CPU/RAM, computes optimal llama-server options and
// persists them through the same validation path as saveModelConfig, returning
// the applied ModelConfig
export async function tuneModelConfig(modelID: string): Promise<any> {
  return app().TuneModelConfig(modelID)
}

// ModelBenchResult mirrors the backend core.ModelBenchResult: the measured
// token-generation throughput (tgTps) plus the effective parameters the
// llama-bench run used (ngl as reported, threads where 0 = auto/omitted,
// usedCpuMoe=false when the run fell back to no cpu-moe flags) and the
// wall-clock duration of the measured run (elapsedS)
export interface ModelBenchResult {
  tgTps: number
  ngl: string
  threads: number
  usedCpuMoe: boolean
  elapsedS: number
}

// Deep-benchmark the model's real decode speed with the llama-bench binary
// installed next to llama-server, using the model's currently saved config.
// The run loads the full model and may take minutes — user-triggered only,
// single-flight on the backend (a concurrent second call waits).
export async function benchmarkModel(modelID: string): Promise<ModelBenchResult> {
  return app().BenchmarkModel(modelID)
}

// ─── Server ──────────────────────────────────────────────────────

// ServerConfig mirrors the backend core.ServerConfig: accessMode is the service access
// scope ("local" | "lan"), host is the actual listen address derived from accessMode,
// apiKey is the optional llama-server bearer token (empty = no authentication),
// deviceId is the serving-GPU selection (stable nvidia-smi UUID; empty = auto, default CUDA device).
export interface ServerConfig {
  accessMode: string
  host: string
  port: number
  maxModels: number
  cacheRam: number
  apiKey: string
  deviceId: string
}

export async function getServerConfig(): Promise<ServerConfig> {
  return app().GetServerConfig()
}

export async function saveServerConfig(cfg: ServerConfig): Promise<void> {
  return app().SaveServerConfig(cfg)
}

export async function getServerStatus(): Promise<{ running: boolean; log: string[] }> {
  return app().GetServerStatus()
}

// Incremental server-log fetch: returns the ring entries appended since the
// given cursor (seq >= since; 0 = everything retained) plus the next cursor
// value to pass on the following call. Lines already evicted from the backend
// ring cannot be recovered — when next - since exceeds the ring cap the
// caller must refetch from 0 (see lib/serverLog.ts).
export async function getServerLogsSince(since: number): Promise<{ entries: ServerLogEntry[]; next: number }> {
  return app().GetServerLogsSince(since)
}

export async function startServer(): Promise<void> {
  return app().StartServer()
}

// Start the llama-server service for one specific model. Desktop (router
// mode) ignores the model and lazy-loads as before; Android (direct mode)
// makes it the single resident model — a running server with the same model
// is a no-op, a different one restarts the service.
export async function startServerWithModel(model: string): Promise<void> {
  return app().StartServerWithModel(model)
}

export async function stopServer(): Promise<void> {
  return app().StopServer()
}

// ─── llama.cpp Download ──────────────────────────────────────────

export async function getLlamaCppDownloadStatus(): Promise<any> {
  return app().GetLlamaCppDownloadStatus()
}

export async function startLlamaCppDownload(): Promise<void> {
  return app().StartLlamaCppDownload()
}

export async function pauseLlamaCppDownload(): Promise<void> {
  return app().PauseLlamaCppDownload()
}

export async function resumeLlamaCppDownload(): Promise<void> {
  return app().ResumeLlamaCppDownload()
}

export async function stopLlamaCppDownload(): Promise<void> {
  return app().StopLlamaCppDownload()
}

export async function browseLlamaCppDir(): Promise<string> {
  return app().BrowseLlamaCppDir()
}

// Choose the llama.cpp download path: opens the system folder picker, persists the
// choice, and returns the selected directory string (empty string when cancelled)
export async function browseLlamaCppDownloadDir(): Promise<string> {
  return app().BrowseLlamaCppDownloadDir()
}

// Choose the models directory: opens the system folder picker and returns the selected
// directory string (empty string when the dialog is cancelled)
export async function browseModelsDir(): Promise<string> {
  return app().BrowseModelsDir()
}

// Choose the model download path: opens the system folder picker, persists the
// choice, and returns the selected directory string (empty string when cancelled)
export async function browseModelDownloadDir(): Promise<string> {
  return app().BrowseModelDownloadDir()
}

// ─── App Update ──────────────────────────────────────────────────

export async function getAppVersion(): Promise<string> {
  return app().GetAppVersion()
}

export async function checkForUpdate(): Promise<{ hasUpdate: boolean; version: string; notes: string; published: string }> {
  return app().CheckForUpdate()
}

export async function startUpdateDownload(version: string): Promise<void> {
  return app().StartUpdateDownload(version)
}

export async function getUpdateDownloadStatus(): Promise<{ status: string; progress: number; total: number; downloaded: number; version: string; filePath: string; error: string; kind: string; installer: boolean }> {
  return app().GetUpdateDownloadStatus()
}

export async function stopUpdateDownload(): Promise<void> {
  return app().StopUpdateDownload()
}

// Launch the downloaded setup installer and exit the app (user confirmed
// "install now"); rejects when the download is not a finished installer
export async function installUpdate(): Promise<void> {
  return app().InstallUpdate()
}

// ─── Downloads (HF Mirror) ───────────────────────────────────────

export async function searchDownloads(query: string, filter: string): Promise<any[]> {
  return app().SearchDownloads(query, filter)
}

export async function getModelFiles(modelID: string): Promise<any[]> {
  return app().GetModelFiles(modelID)
}

// Get the model's largest GGUF file size (bytes) for the search card display;
// 0 means no GGUF or query failure, handled silently by the caller
export async function getModelMaxFileSize(modelID: string): Promise<number> {
  return app().GetModelMaxFileSize(modelID)
}

// Get the first paragraph of the model README (<=200 chars); returns an error when
// there is no README or the read fails, handled silently by the caller
export async function getModelDescription(modelID: string): Promise<string> {
  return app().GetModelDescription(modelID)
}

export async function startDownload(modelID: string, files: string[]): Promise<void> {
  return app().StartDownload(modelID, files)
}

export async function getDownloadTasks(): Promise<any[]> {
  return app().GetDownloadTasks()
}

export async function cancelDownloadTask(id: string): Promise<void> {
  return app().CancelDownloadTask(id)
}

export async function retryDownloadTask(id: string): Promise<void> {
  return app().RetryDownloadTask(id)
}

export async function pauseDownloadTask(id: string): Promise<void> {
  return app().PauseDownloadTask(id)
}

export async function resumeDownloadTask(id: string): Promise<void> {
  return app().ResumeDownloadTask(id)
}

// ─── Download Source ─────────────────────────────────────────────

// Current model download source ("hf" | "huggingface" | "modelscope"); decides which mirror backend search and download use
export async function getDownloadSource(): Promise<string> {
  return app().GetDownloadSource()
}

export async function setDownloadSource(source: string): Promise<void> {
  return app().SetDownloadSource(source)
}

// ─── Router Models (TaskDock in-memory model list + unload) ─────────────────

// LoadedModel mirrors the backend core.LoadedModel: id / type (chat|audio|image|video) / status (loaded|loading|sleeping)
export interface LoadedModel { id: string; type: string; status: string }

// getLoadedModels queries the llama-server router for models currently loaded /
// loading / sleeping; returns an empty array when the service is not running or the
// query fails (the frontend polls and retries).
export async function getLoadedModels(): Promise<LoadedModel[]> {
  return (await app().GetLoadedModels()) ?? []
}

// unloadModel sends a model unload request to llama-server; on failure the frontend shows the error inline.
export async function unloadModel(id: string): Promise<void> {
  return app().UnloadModel(id)
}

// ─── Remote Docs (Docs page remote-first content) ────────────────────────────

// RemoteDocResult mirrors the backend core.RemoteDocResult: text is the markdown
// body (empty when source is "none"), source is the tier that produced it
// ("online" | "cache" | "none") and fetchedAt is the RFC3339 timestamp of the
// fetch that produced text ("" when none)
export interface RemoteDocResult {
  text: string
  source: 'online' | 'cache' | 'none'
  fetchedAt: string
}

// getRemoteDoc fetches one docs section's latest markdown from this repo's main
// branch with the online → disk cache fallback decided on the backend (the
// bundled tier stays in the frontend). Network unavailability is an expected
// state, not an error: it resolves with source "none" or a cache hit; the call
// rejects only for invalid arguments.
export async function getRemoteDoc(lang: 'zh' | 'en', sectionId: string, force = false): Promise<RemoteDocResult> {
  return app().GetRemoteDoc(lang, sectionId, force)
}
