// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails application struct whose methods are bound to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BenchmarkModel measures the real token-generation speed of modelID on this
 * machine by running the llama-bench binary installed next to llama-server
 * with the model's CURRENT SAVED ModelConfig (a model without a saved config
 * uses defaultModelConfig). Minutes-long and model-loading by nature, it is
 * strictly user-triggered (no auto-triggers anywhere), single-flight via
 * benchRunMu — wait-then-run: a concurrent second call blocks and then runs
 * its own measurement — and bounded by benchRunTimeout per invocation.
 *
 * cpu-moe configs try the optional-flag shapes in order, stopping at the
 * first success (non-cpu-moe configs run the single no-flags attempt; there
 * is nothing to retry):
 *  1. --cpu-moe — the llama-server flag shape, future-proofing newer
 *     llama-bench builds that accept it (UsedCPUMoe=true),
 *  2. -ncmoe <blockCount+1> — all MoE expert layers on the CPU, the closest
 *     llama-bench equivalent of --cpu-moe; needs readable GGUF metrics with
 *     a layer count, otherwise this step is skipped (UsedCPUMoe=true),
 *  3. no optional flags — last resort; the measured placement then differs
 *     from the saved config and UsedCPUMoe=false records it.
 *
 * Each attempt is logged at [INFO] (intermediate failures at [WARN]); only
 * the final attempt's failure is surfaced as the error.
 */
export function BenchmarkModel(modelID: string): $CancellablePromise<$models.ModelBenchResult> {
    return $Call.ByID(1960463204, modelID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function BrowseLlamaCppDir(): $CancellablePromise<string> {
    return $Call.ByID(3350014259);
}

/**
 * BrowseLlamaCppDownloadDir opens a system directory chooser to pick the
 * llama.cpp download path; returns empty string and nil on cancel, and on
 * success performs the same write as SetLlamaCppDownloadDir and returns the
 * chosen directory.
 */
export function BrowseLlamaCppDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(2305276219);
}

/**
 * BrowseModelDownloadDir opens a system directory chooser to pick the model
 * download path; returns empty string and nil on cancel, and on success
 * performs the same write as SetModelDownloadDir and returns the chosen
 * directory.
 */
export function BrowseModelDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(1383777610);
}

/**
 * BrowseModelsDir opens a system directory chooser to pick the model
 * directory; returns empty string and nil on cancel, and on success performs
 * the same validation and write as SetModelsDir and returns the chosen
 * directory.
 */
export function BrowseModelsDir(): $CancellablePromise<string> {
    return $Call.ByID(3452550715);
}

export function CancelDownloadTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1195596959, id);
}

/**
 * CheckForUpdate queries the remote repo latest release and returns whether a
 * new version exists along with version info.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateCheckResult | null> {
    return $Call.ByID(2837150318).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAppVersion returns the current app version (aligned with GitHub release
 * tags).
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(323973705);
}

export function GetCPU(): $CancellablePromise<$models.CPUInfo | null> {
    return $Call.ByID(2051216158).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetCUDA(): $CancellablePromise<$models.CUDAInfo | null> {
    return $Call.ByID(3549453655).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetConfig(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(955128306).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetDisk(): $CancellablePromise<$models.DiskUsage | null> {
    return $Call.ByID(3567524009).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetDownloadSource returns the current model download source ("hf" | "modelscope").
 */
export function GetDownloadSource(): $CancellablePromise<string> {
    return $Call.ByID(779669993);
}

export function GetDownloadTasks(): $CancellablePromise<$models.DlTask[]> {
    return $Call.ByID(471464974).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetGPU(): $CancellablePromise<$models.GPUInfo[]> {
    return $Call.ByID(3317380266).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetLlamaCpp(): $CancellablePromise<$models.LlamaCppInfo | null> {
    return $Call.ByID(1558827786).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetLlamaCppDownloadStatus(): $CancellablePromise<$models.DownloadState | null> {
    return $Call.ByID(2430553188).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetLoadedModels queries the llama-server router for the list of loaded /
 * loading / sleeping models. Returns nil when the server is not running
 * (frontend wails.ts normalizes to an empty array); on query failure it logs
 * a warning and returns nil (transient connection issues are not reported to
 * the frontend, retried by polling).
 */
export function GetLoadedModels(): $CancellablePromise<$models.LoadedModel[]> {
    return $Call.ByID(2052539751).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetMemory(): $CancellablePromise<$models.MemoryInfo | null> {
    return $Call.ByID(3935674743).then(($result: any) => {
        return $$createType21($result);
    });
}

export function GetModelConfig(modelID: string): $CancellablePromise<$models.ModelConfig> {
    return $Call.ByID(3379369827, modelID).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * GetModelDescription fetches the natural-language description from a model's
 * README (shown on the download page). Routed to HF or ModelScope README
 * endpoint by current download source.
 */
export function GetModelDescription(modelID: string): $CancellablePromise<string> {
    return $Call.ByID(2953385413, modelID);
}

/**
 * GetModelFiles routes the file list by current download source: modelscope
 * → listModelScopeFiles, otherwise (default hf) → getHFModelFiles.
 */
export function GetModelFiles(modelID: string): $CancellablePromise<$models.HFFileOut[]> {
    return $Call.ByID(3059698428, modelID).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * GetModelMaxFileSize returns the largest GGUF file size for a model (shown
 * on the search card). modelscope source derives it from the file list; hf
 * source uses the details endpoint (blobs=true for real sizes).
 */
export function GetModelMaxFileSize(modelID: string): $CancellablePromise<number> {
    return $Call.ByID(3502311522, modelID);
}

export function GetModels(): $CancellablePromise<$models.ModelInfo[]> {
    return $Call.ByID(3623107510).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * GetMonitorStatus returns the realtime monitoring sample snapshot (CPU/
 * memory / GPU are cached by the background sampler; ServerRunning / TPS /
 * UptimeSeconds are fetched live).
 */
export function GetMonitorStatus(): $CancellablePromise<$models.MonitorStatus | null> {
    return $Call.ByID(1406400820).then(($result: any) => {
        return $$createType28($result);
    });
}

export function GetOS(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1828890902).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * GetRemoteDoc fetches one docs section's latest markdown for the Docs page's
 * remote-first content path (online → disk cache → bundled fallback decided
 * here; the bundled tier lives in the frontend). See the file header for the
 * error contract: errors are returned ONLY for invalid arguments — network
 * unavailability is an expected state reported through Source "cache"/"none".
 */
export function GetRemoteDoc(lang: string, sectionID: string, force: boolean): $CancellablePromise<$models.RemoteDocResult> {
    return $Call.ByID(2670577276, lang, sectionID, force).then(($result: any) => {
        return $$createType30($result);
    });
}

/**
 * GetSafeArea returns the current system-bar insets in physical pixels
 * (Android only: status-bar/cutout band on top, gesture/nav bar on the
 * bottom; zeros on every other platform). Feeds the frontend's safe-area CSS
 * layer, which takes the max of this and the env(safe-area-inset-*) insets —
 * a zero result stays a no-op on desktop.
 */
export function GetSafeArea(): $CancellablePromise<$models.SafeArea> {
    return $Call.ByID(4054609944).then(($result: any) => {
        return $$createType31($result);
    });
}

export function GetServerConfig(): $CancellablePromise<$models.ServerConfig> {
    return $Call.ByID(922492437).then(($result: any) => {
        return $$createType32($result);
    });
}

/**
 * GetServerLogsSince returns the retained log lines with Seq >= since plus
 * the next cursor value for the following call (a since of 0 returns
 * everything retained, up to the ring cap of serverLogsCap lines). Lines
 * already evicted from the ring cannot be recovered: the caller detects that
 * case (next - since > serverLogsCap) and refetches from 0.
 */
export function GetServerLogsSince(since: number): $CancellablePromise<$models.ServerLogsPage> {
    return $Call.ByID(2272125646, since).then(($result: any) => {
        return $$createType33($result);
    });
}

export function GetServerStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2805866625).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetSystemInfo(): $CancellablePromise<$models.SystemInfo | null> {
    return $Call.ByID(1207510045).then(($result: any) => {
        return $$createType35($result);
    });
}

/**
 * GetUpdateDownloadStatus returns the current state and progress of the
 * update download.
 */
export function GetUpdateDownloadStatus(): $CancellablePromise<$models.UpdateDownloadState | null> {
    return $Call.ByID(1961990283).then(($result: any) => {
        return $$createType37($result);
    });
}

/**
 * InstallUpdate launches the downloaded setup installer and exits the app so
 * the installer can complete the update (user confirmed "install now" in the
 * update modal). Only valid for a completed download of the installer
 * artifact; see installUpdateNow for the guards.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2348643066);
}

export function PauseDownloadTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(2431111255, id);
}

export function PauseLlamaCppDownload(): $CancellablePromise<void> {
    return $Call.ByID(2029097948);
}

export function RefreshModels(): $CancellablePromise<$models.ModelInfo[]> {
    return $Call.ByID(879778009).then(($result: any) => {
        return $$createType26($result);
    });
}

export function ResumeDownloadTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1327992246, id);
}

export function ResumeLlamaCppDownload(): $CancellablePromise<void> {
    return $Call.ByID(3234250677);
}

/**
 * RetryDownloadTask retries a download task: for finished tasks
 * (error/cancelled/done) or queued tasks, it rebuilds the ctx and restarts
 * the download goroutine; downloadTask checks .part file size as the resume
 * offset, naturally reusing resume capability. Tasks that are still
 * downloading or paused have an active goroutine, so retrying is disallowed
 * to prevent concurrent writes to the same .part file; when the id is not
 * found, returns nil silently, matching CancelDownloadTask semantics.
 */
export function RetryDownloadTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1684922999, id);
}

export function SaveModelConfig(modelID: string, config: $models.ModelConfig): $CancellablePromise<void> {
    return $Call.ByID(2454186708, modelID, config);
}

export function SaveServerConfig(cfg: $models.ServerConfig): $CancellablePromise<void> {
    return $Call.ByID(2386255100, cfg);
}

/**
 * SearchDownloads routes the search by current download source: modelscope
 * → searchModelScopeAt, otherwise (default hf) → searchHFMirror.
 */
export function SearchDownloads(query: string, filter: string): $CancellablePromise<$models.HFSearchResult[]> {
    return $Call.ByID(3752716797, query, filter).then(($result: any) => {
        return $$createType39($result);
    });
}

/**
 * SetApiRouteMode toggles API-route (headless) mode. Enabling persists the
 * preference, hands a running llama-server over to the successor process
 * (handover file), relaunches the app with --headless, marks the upcoming
 * shutdown as a mode switch (Shutdown then keeps the service and downloads
 * alive) and quits the GUI — the WebView2 process tree is released and only
 * the Go backend + tray + llama-server remain. Disabling just persists the
 * flag: the GUI toggle always starts from false (the headless "Show Main
 * Window" path resets it itself before relaunching the GUI). Enabling is
 * rejected while the system tray is disabled: the tray menu is the only way
 * back from headless mode, so without it the headless process would have no
 * visible entry point at all. Dev builds (wails dev) reject enabling
 * outright: the relaunch-based switch escapes the wails dev supervisor and
 * tears the dev session down (binary lock + dead vite server), so the
 * feature must be exercised on a `wails build` production binary.
 */
export function SetApiRouteMode(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1452625074, enabled);
}

/**
 * SetDownloadSource sets the model download source: only hf / huggingface /
 * modelscope allowlist values are permitted; illegal values return an error
 * without mutating state; valid values are written to the global and persisted.
 */
export function SetDownloadSource(source: string): $CancellablePromise<void> {
    return $Call.ByID(2913750285, source);
}

/**
 * SetLanguage sets the UI language: only zh / en / auto allowlist values are
 * permitted; illegal values return an error without mutating state; valid
 * values are written to the global and persisted, and the effective language
 * is returned (zh/en; auto resolves to the system detection result). The
 * frontend uses the return value to refresh UI text immediately, avoiding a
 * second read from GetConfig.
 */
export function SetLanguage(language: string): $CancellablePromise<string> {
    return $Call.ByID(605496818, language);
}

/**
 * SetLlamaCppDownloadDir sets the directory new llama.cpp downloads are
 * extracted into: any non-empty path is accepted, written to the global,
 * persisted, and the llama.cpp detection cache is invalidated so the new
 * install is picked up immediately.
 */
export function SetLlamaCppDownloadDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1234016213, dir);
}

/**
 * SetModelDownloadDir sets the directory new model downloads land in: any
 * non-empty path is accepted (a fresh path is a valid target for the next
 * download), written to the global, persisted, and the model cache is
 * invalidated so the merged model list reflects the new download root.
 */
export function SetModelDownloadDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(714764088, dir);
}

/**
 * SetModelsDir sets the custom model directory: valid directories are written
 * to global state, persisted to config, and the model cache is invalidated
 * (next GetModels rescans with the new directory); illegal input returns an
 * error without mutating state.
 */
export function SetModelsDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1326214329, dir);
}

/**
 * SetOnboardingDismissed marks the Home page quick-start checklist as
 * dismissed (manually closed or auto-completed): writes to global state and
 * persists to config. Pure UI preference with no side effects, mirroring
 * SetSidebarCollapsed.
 */
export function SetOnboardingDismissed(dismissed: boolean): $CancellablePromise<void> {
    return $Call.ByID(799206670, dismissed);
}

/**
 * SetSidebarCollapsed sets the sidebar collapsed/expanded preference: writes
 * to global state and persists to config; no side effects like window
 * background changes (pure UI preference, mirroring the minimal form of
 * SetTheme).
 */
export function SetSidebarCollapsed(collapsed: boolean): $CancellablePromise<void> {
    return $Call.ByID(4236638085, collapsed);
}

export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(1709326749, theme);
}

/**
 * SetTrayEnabled sets the system tray toggle: persists the preference to
 * config; on Windows and macOS it starts/stops the tray according to the
 * persisted value, on other platforms it only persists (the callers no-op —
 * see trayPlatformSupported). Concurrency-safe (configMu and trayMu guard
 * global state), called by the frontend settings page system tray toggle.
 *
 * Note: the tray is one-shot per process (the old fyne.io/systray had a
 * package-level quitOnce, and the v3 SystemTray tray deliberately keeps the
 * same semantics — see the trayStarted comment in core/tray.go) — so when
 * enabling the tray, InitTray is only called to start a tray that has not
 * started yet (idempotent); when disabling the tray, QuitTray removes the
 * icon and the tray will not restart in this process. Re-enabling takes
 * effect after an app restart.
 */
export function SetTrayEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3214759057, enabled);
}

export function StartDownload(modelID: string, files: string[]): $CancellablePromise<void> {
    return $Call.ByID(2707618076, modelID, files);
}

export function StartLlamaCppDownload(): $CancellablePromise<void> {
    return $Call.ByID(2611530074);
}

export function StartServer(): $CancellablePromise<void> {
    return $Call.ByID(4115957591);
}

/**
 * StartServerWithModel starts the service for one specific model. Desktop
 * (router mode) ignores the model and keeps the StartServer already-running
 * no-op; on Android (direct mode) the model becomes the single resident: a
 * running server with the same model is a no-op, a different one restarts
 * the service. Idempotent on both platforms.
 */
export function StartServerWithModel(model: string): $CancellablePromise<void> {
    return $Call.ByID(1420164860, model);
}

/**
 * StartUpdateDownload starts downloading the new version exe to the same
 * directory as the executable. The version is passed by the caller (from the
 * CheckForUpdate result) and is used for target file naming.
 */
export function StartUpdateDownload(version: string): $CancellablePromise<void> {
    return $Call.ByID(2696931657, version);
}

export function StopLlamaCppDownload(): $CancellablePromise<void> {
    return $Call.ByID(1564418742);
}

export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(3351777243);
}

/**
 * StopUpdateDownload cancels the in-flight update download (user-initiated
 * stop / app exit).
 */
export function StopUpdateDownload(): $CancellablePromise<void> {
    return $Call.ByID(1678582909);
}

/**
 * TuneModelConfig computes hardware-aware optimal inference parameters for the
 * model (GGUF metrics + GPU/CPU/RAM snapshot), persists them via SaveModelConfig
 * validation, and returns the applied config.
 */
export function TuneModelConfig(modelID: string): $CancellablePromise<$models.ModelConfig> {
    return $Call.ByID(769524497, modelID).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * UnloadModel sends a model unload request to llama-server. Returns error
 * when the server is not running; returns invalid-parameter error when id is
 * empty.
 */
export function UnloadModel(id: string): $CancellablePromise<void> {
    return $Call.ByID(2623847304, id);
}

// Private type creation functions
const $$createType0 = $models.ModelBenchResult.createFrom;
const $$createType1 = $models.UpdateCheckResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.CPUInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.CUDAInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $models.DiskUsage.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.DlTask.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.GPUInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.LlamaCppInfo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.DownloadState.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.LoadedModel.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.MemoryInfo.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $models.ModelConfig.createFrom;
const $$createType23 = $models.HFFileOut.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.ModelInfo.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.MonitorStatus.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = $Create.Map($Create.Any, $Create.Any);
const $$createType30 = $models.RemoteDocResult.createFrom;
const $$createType31 = $models.SafeArea.createFrom;
const $$createType32 = $models.ServerConfig.createFrom;
const $$createType33 = $models.ServerLogsPage.createFrom;
const $$createType34 = $models.SystemInfo.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = $models.UpdateDownloadState.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = $models.HFSearchResult.createFrom;
const $$createType39 = $Create.Array($$createType38);
