// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CPUInfo {
    "model": string;
    "cores": number;
    "logicalCpus": number;

    /** Creates a new CPUInfo instance. */
    constructor($$source: Partial<CPUInfo> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("cores" in $$source)) {
            this["cores"] = 0;
        }
        if (!("logicalCpus" in $$source)) {
            this["logicalCpus"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CPUInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CPUInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CPUInfo($$parsedSource as Partial<CPUInfo>);
    }
}

export class CUDAInfo {
    "available": boolean;
    "driverVersion": string;
    "toolkitVersion": string;

    /** Creates a new CUDAInfo instance. */
    constructor($$source: Partial<CUDAInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("driverVersion" in $$source)) {
            this["driverVersion"] = "";
        }
        if (!("toolkitVersion" in $$source)) {
            this["toolkitVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CUDAInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CUDAInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CUDAInfo($$parsedSource as Partial<CUDAInfo>);
    }
}

/**
 * DiskUsage is the usage of a single disk volume: Path is the volume root
 * (Windows like "C:\", non-Windows like "/"), Used = Total - Free.
 */
export class DiskUsage {
    "path": string;
    "used": number;
    "total": number;

    /** Creates a new DiskUsage instance. */
    constructor($$source: Partial<DiskUsage> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("used" in $$source)) {
            this["used"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): DiskUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskUsage($$parsedSource as Partial<DiskUsage>);
    }
}

export class DlTask {
    "id": string;
    "modelId": string;
    "fileName": string;
    "destDir": string;

    /**
     * download source: hf / modelscope
     */
    "source": string;
    "status": string;
    "progress": number;
    "total": number;
    "downloaded": number;
    "sizeHuman": string;

    /**
     * current download speed (bytes/sec)
     */
    "speed": number;
    "error": string;

    /** Creates a new DlTask instance. */
    constructor($$source: Partial<DlTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("destDir" in $$source)) {
            this["destDir"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("sizeHuman" in $$source)) {
            this["sizeHuman"] = "";
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DlTask instance from a string or object.
     */
    static createFrom($$source: any = {}): DlTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DlTask($$parsedSource as Partial<DlTask>);
    }
}

export class DownloadState {
    /**
     * idle, fetching, downloading, paused, extracting, done, error
     */
    "status": string;
    "paused": boolean;
    "progress": number;
    "total": number;
    "downloaded": number;
    "fileName": string;
    "version": string;
    "error": string;

    /** Creates a new DownloadState instance. */
    constructor($$source: Partial<DownloadState> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadState instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadState($$parsedSource as Partial<DownloadState>);
    }
}

export class GPUInfo {
    "name": string;

    /**
     * Vendor classifies the GPU maker for platform-aware planning (asset
     * selection, auto-tune Metal branch, VRAM display rules):
     * "nvidia" | "intel" | "amd" | "apple" | "" (unknown/legacy probe paths).
     */
    "vendor": string;

    /**
     * UUID is the stable nvidia-smi device identifier ("GPU-xxxx-..."),
     * invariant across reboots and driver index changes; it is the value the
     * serving-GPU selection (ServerConfig.DeviceID / CUDA_VISIBLE_DEVICES) is
     * keyed on. Empty when the probe could not read it (always empty for
     * non-NVIDIA entries: apple / PCI-classified cards carry no UUID).
     */
    "uuid": string;
    "memoryMb": number;
    "memoryUsedMb": number;
    "driverVersion": string;
    "cudaCores": number;
    "computeCapability": number;

    /** Creates a new GPUInfo instance. */
    constructor($$source: Partial<GPUInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("memoryMb" in $$source)) {
            this["memoryMb"] = 0;
        }
        if (!("memoryUsedMb" in $$source)) {
            this["memoryUsedMb"] = 0;
        }
        if (!("driverVersion" in $$source)) {
            this["driverVersion"] = "";
        }
        if (!("cudaCores" in $$source)) {
            this["cudaCores"] = 0;
        }
        if (!("computeCapability" in $$source)) {
            this["computeCapability"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GPUInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GPUInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GPUInfo($$parsedSource as Partial<GPUInfo>);
    }
}

export class HFFile {
    "rfilename": string;
    "size": number;

    /** Creates a new HFFile instance. */
    constructor($$source: Partial<HFFile> = {}) {
        if (!("rfilename" in $$source)) {
            this["rfilename"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HFFile instance from a string or object.
     */
    static createFrom($$source: any = {}): HFFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HFFile($$parsedSource as Partial<HFFile>);
    }
}

/**
 * HFFileOut is the frontend-facing file info with `filename` JSON key.
 */
export class HFFileOut {
    "filename": string;
    "size": number;

    /** Creates a new HFFileOut instance. */
    constructor($$source: Partial<HFFileOut> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HFFileOut instance from a string or object.
     */
    static createFrom($$source: any = {}): HFFileOut {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HFFileOut($$parsedSource as Partial<HFFileOut>);
    }
}

export class HFSearchResult {
    "id": string;
    "modelId": string;
    "author": string;
    "downloads": number;
    "likes": number;
    "pipelineTag": string;
    "tags": string[];
    "siblings": HFFile[];

    /** Creates a new HFSearchResult instance. */
    constructor($$source: Partial<HFSearchResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("downloads" in $$source)) {
            this["downloads"] = 0;
        }
        if (!("likes" in $$source)) {
            this["likes"] = 0;
        }
        if (!("pipelineTag" in $$source)) {
            this["pipelineTag"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("siblings" in $$source)) {
            this["siblings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HFSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HFSearchResult {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("siblings" in $$parsedSource) {
            $$parsedSource["siblings"] = $$createField7_0($$parsedSource["siblings"]);
        }
        return new HFSearchResult($$parsedSource as Partial<HFSearchResult>);
    }
}

export class LlamaCppInfo {
    "installed": boolean;
    "path": string;
    "version": string;

    /**
     * CudartInstalled reports whether the CUDA runtime DLLs (cudart/cublas,
     * co-downloaded with CUDA builds since llama.cpp b10342) sit next to the
     * resolved binary; always false on non-Windows and for CPU/Vulkan builds.
     */
    "cudartInstalled": boolean;

    /**
     * CudartVersion is the CUDA major family of the installed cudart runtime
     * ("13", "12"), derived from the cudart64_*.dll file name. The DLL's
     * embedded FileVersion does not encode the CUDA release version, so the
     * file name is the only reliable source; a bare "12" cannot prove the
     * 12.8 Blackwell floor. Empty when not installed, unparsable, or
     * non-Windows.
     */
    "cudartVersion": string;

    /**
     * Accel names the acceleration backend of the installed build:
     * "cuda" | "vulkan" | "metal" | "cpu". Official llama.cpp builds are
     * GGML_BACKEND_DL everywhere, so the value is detected from the backend
     * library sitting next to the resolved binary (windows ggml-cuda.dll /
     * ggml-vulkan.dll, linux libggml-vulkan.so), from the arch on darwin
     * (arm64 release embeds Metal; x64 release is CPU-only) or the platform
     * default (android = CPU-only). Empty when llama.cpp is not installed.
     */
    "accel": string;

    /** Creates a new LlamaCppInfo instance. */
    constructor($$source: Partial<LlamaCppInfo> = {}) {
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("cudartInstalled" in $$source)) {
            this["cudartInstalled"] = false;
        }
        if (!("cudartVersion" in $$source)) {
            this["cudartVersion"] = "";
        }
        if (!("accel" in $$source)) {
            this["accel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LlamaCppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LlamaCppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LlamaCppInfo($$parsedSource as Partial<LlamaCppInfo>);
    }
}

/**
 * LoadedModel represents a model entry currently loaded / loading / sleeping
 * in the router.
 */
export class LoadedModel {
    /**
     * Model ID (matches API response id)
     */
    "id": string;

    /**
     * Model type: chat | audio | image | video
     */
    "type": string;

    /**
     * loaded | loading | sleeping
     */
    "status": string;

    /** Creates a new LoadedModel instance. */
    constructor($$source: Partial<LoadedModel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadedModel instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadedModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadedModel($$parsedSource as Partial<LoadedModel>);
    }
}

export class MemoryInfo {
    "totalGb": number;
    "freeGb": number;

    /** Creates a new MemoryInfo instance. */
    constructor($$source: Partial<MemoryInfo> = {}) {
        if (!("totalGb" in $$source)) {
            this["totalGb"] = 0;
        }
        if (!("freeGb" in $$source)) {
            this["freeGb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryInfo($$parsedSource as Partial<MemoryInfo>);
    }
}

/**
 * ModelBenchResult is the display-only outcome of one deep benchmark run
 * (not persisted in v1): the measured token-generation throughput plus the
 * effective parameters the benchmark ran with and its wall-clock duration.
 * UsedCPUMoe reports whether the MoE experts were measured on the CPU
 * (--cpu-moe accepted, or the -ncmoe fallback); false means the run fell back
 * to no optional cpu-moe flags, so the measured placement differs from the
 * saved config.
 */
export class ModelBenchResult {
    "tgTps": number;
    "ngl": string;
    "threads": number;
    "usedCpuMoe": boolean;
    "elapsedS": number;

    /** Creates a new ModelBenchResult instance. */
    constructor($$source: Partial<ModelBenchResult> = {}) {
        if (!("tgTps" in $$source)) {
            this["tgTps"] = 0;
        }
        if (!("ngl" in $$source)) {
            this["ngl"] = "";
        }
        if (!("threads" in $$source)) {
            this["threads"] = 0;
        }
        if (!("usedCpuMoe" in $$source)) {
            this["usedCpuMoe"] = false;
        }
        if (!("elapsedS" in $$source)) {
            this["elapsedS"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelBenchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelBenchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelBenchResult($$parsedSource as Partial<ModelBenchResult>);
    }
}

export class ModelConfig {
    "threads": number;
    "gpuLayers": string;
    "ctxSize": number;
    "batchSize": number;
    "ubatchSize": number;
    "flashAttn": boolean;
    "cacheTypeK": string;
    "cacheTypeV": string;

    /**
     * "", none, mmap, mlock, mmap+mlock, dio
     */
    "loadMode": string;

    /**
     * keep all MoE experts on CPU
     */
    "cpuMoe": boolean;

    /**
     * keep first N MoE layers on CPU, 0=disabled
     */
    "nCpuMoe": number;

    /**
     * "", none, layer, row, tensor
     */
    "splitMode": string;

    /**
     * e.g. "3,1"
     */
    "tensorSplit": string;

    /**
     * default 0
     */
    "mainGpu": number;

    /**
     * "", none, linear, yarn
     */
    "ropeScaling": string;

    /**
     * 0=disabled
     */
    "ropeScale": number;

    /**
     * explicit mmproj path override, empty=auto-detect
     */
    "mmproj": string;

    /**
     * disable thinking (writes reasoning = off)
     */
    "reasoning": boolean;

    /**
     * "", draft-mtp
     */
    "specType": string;

    /**
     * >0 writes spec-draft-n-max
     */
    "specDraftNMax": number;

    /**
     * deprecated, kept only to migrate old configs
     */
    "mlock"?: boolean;

    /**
     * deprecated, kept only to migrate old configs
     */
    "noMmap"?: boolean;

    /** Creates a new ModelConfig instance. */
    constructor($$source: Partial<ModelConfig> = {}) {
        if (!("threads" in $$source)) {
            this["threads"] = 0;
        }
        if (!("gpuLayers" in $$source)) {
            this["gpuLayers"] = "";
        }
        if (!("ctxSize" in $$source)) {
            this["ctxSize"] = 0;
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }
        if (!("ubatchSize" in $$source)) {
            this["ubatchSize"] = 0;
        }
        if (!("flashAttn" in $$source)) {
            this["flashAttn"] = false;
        }
        if (!("cacheTypeK" in $$source)) {
            this["cacheTypeK"] = "";
        }
        if (!("cacheTypeV" in $$source)) {
            this["cacheTypeV"] = "";
        }
        if (!("loadMode" in $$source)) {
            this["loadMode"] = "";
        }
        if (!("cpuMoe" in $$source)) {
            this["cpuMoe"] = false;
        }
        if (!("nCpuMoe" in $$source)) {
            this["nCpuMoe"] = 0;
        }
        if (!("splitMode" in $$source)) {
            this["splitMode"] = "";
        }
        if (!("tensorSplit" in $$source)) {
            this["tensorSplit"] = "";
        }
        if (!("mainGpu" in $$source)) {
            this["mainGpu"] = 0;
        }
        if (!("ropeScaling" in $$source)) {
            this["ropeScaling"] = "";
        }
        if (!("ropeScale" in $$source)) {
            this["ropeScale"] = 0;
        }
        if (!("mmproj" in $$source)) {
            this["mmproj"] = "";
        }
        if (!("reasoning" in $$source)) {
            this["reasoning"] = false;
        }
        if (!("specType" in $$source)) {
            this["specType"] = "";
        }
        if (!("specDraftNMax" in $$source)) {
            this["specDraftNMax"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelConfig($$parsedSource as Partial<ModelConfig>);
    }
}

export class ModelInfo {
    "author": string;
    "name": string;
    "path": string;
    "sizeBytes": number;
    "sizeHuman": string;
    "architecture": string;
    "quantization": string;
    "hasMmproj": boolean;

    /**
     * SourceDir is the root directory the model was scanned from (the model
     * download directory or the user-imported model directory). Lets the
     * frontend show which of the two sources a model belongs to when both are
     * configured.
     */
    "sourceDir": string;

    /**
     * Alias is the llama-server model id for this model: the display Name
     * sanitized for INI section use with its original casing preserved, plus a
     * deterministic -2/-3 suffix on case-insensitive collisions (see
     * aliasDedup). The API page shows it so users copy-paste an id that
     * llama-server matches exactly (model lookup is case-sensitive).
     */
    "alias": string;

    /** Creates a new ModelInfo instance. */
    constructor($$source: Partial<ModelInfo> = {}) {
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("sizeHuman" in $$source)) {
            this["sizeHuman"] = "";
        }
        if (!("architecture" in $$source)) {
            this["architecture"] = "";
        }
        if (!("quantization" in $$source)) {
            this["quantization"] = "";
        }
        if (!("hasMmproj" in $$source)) {
            this["hasMmproj"] = false;
        }
        if (!("sourceDir" in $$source)) {
            this["sourceDir"] = "";
        }
        if (!("alias" in $$source)) {
            this["alias"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo($$parsedSource as Partial<ModelInfo>);
    }
}

/**
 * MonitorGPU is the per-GPU monitoring data (sampled via nvidia-smi).
 */
export class MonitorGPU {
    "index": number;
    "name": string;
    "utilPercent": number;
    "memUsed": number;
    "memTotal": number;

    /** Creates a new MonitorGPU instance. */
    constructor($$source: Partial<MonitorGPU> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("utilPercent" in $$source)) {
            this["utilPercent"] = 0;
        }
        if (!("memUsed" in $$source)) {
            this["memUsed"] = 0;
        }
        if (!("memTotal" in $$source)) {
            this["memTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorGPU instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorGPU {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorGPU($$parsedSource as Partial<MonitorGPU>);
    }
}

/**
 * MonitorStatus is the JSON contract returned to the frontend by
 * GetMonitorStatus; fields match frontend/src/lib/monitor.ts MonitorStatus
 * one-to-one, so changes must sync on both sides.
 */
export class MonitorStatus {
    "cpuPercent": number;
    "memUsed": number;
    "memTotal": number;
    "gpus": MonitorGPU[];
    "serverRunning": boolean;
    "promptTps": number;
    "decodeTps": number;
    "uptimeSeconds": number;

    /**
     * Disk is the disk usage of the volume containing the model directory;
     * nil when sampling fails (frontend hides the disk row), and it never
     * blocks other sampling metrics.
     */
    "disk": DiskUsage | null;

    /** Creates a new MonitorStatus instance. */
    constructor($$source: Partial<MonitorStatus> = {}) {
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("memUsed" in $$source)) {
            this["memUsed"] = 0;
        }
        if (!("memTotal" in $$source)) {
            this["memTotal"] = 0;
        }
        if (!("gpus" in $$source)) {
            this["gpus"] = [];
        }
        if (!("serverRunning" in $$source)) {
            this["serverRunning"] = false;
        }
        if (!("promptTps" in $$source)) {
            this["promptTps"] = 0;
        }
        if (!("decodeTps" in $$source)) {
            this["decodeTps"] = 0;
        }
        if (!("uptimeSeconds" in $$source)) {
            this["uptimeSeconds"] = 0;
        }
        if (!("disk" in $$source)) {
            this["disk"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorStatus {
        const $$createField3_0 = $$createType4;
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("gpus" in $$parsedSource) {
            $$parsedSource["gpus"] = $$createField3_0($$parsedSource["gpus"]);
        }
        if ("disk" in $$parsedSource) {
            $$parsedSource["disk"] = $$createField8_0($$parsedSource["disk"]);
        }
        return new MonitorStatus($$parsedSource as Partial<MonitorStatus>);
    }
}

/**
 * RemoteDocResult is one docs section fetch outcome: the markdown body (empty
 * when Source is "none"), which tier produced it, and the RFC3339 timestamp of
 * the fetch that produced Text ("" when none — the frontend only shows it for
 * the "cache" badge).
 */
export class RemoteDocResult {
    "text": string;
    "source": string;
    "fetchedAt": string;

    /** Creates a new RemoteDocResult instance. */
    constructor($$source: Partial<RemoteDocResult> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteDocResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteDocResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteDocResult($$parsedSource as Partial<RemoteDocResult>);
    }
}

export class ServerConfig {
    /**
     * AccessMode is the service access scope ("local" | "lan", default
     * "local"); Host is the derived actual listen address per AccessMode and
     * never takes direct user input.
     */
    "accessMode": string;
    "host": string;
    "port": number;
    "maxModels": number;
    "cacheRam": number;

    /**
     * APIKey is the optional llama-server --api-key bearer token; empty means
     * no authentication (default, current behavior).
     */
    "apiKey": string;

    /**
     * DeviceID is the serving-GPU selection: the stable nvidia-smi UUID of the
     * GPU llama-server is pinned to via CUDA_VISIBLE_DEVICES (see
     * bridge.cudaDeviceEnv). Empty means auto (CUDA default device order, the
     * historical behavior). Non-empty values are validated against the current
     * GPU probe list in SaveServerConfig; old configs missing the field load
     * as "" (auto) naturally.
     */
    "deviceId": string;

    /** Creates a new ServerConfig instance. */
    constructor($$source: Partial<ServerConfig> = {}) {
        if (!("accessMode" in $$source)) {
            this["accessMode"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("maxModels" in $$source)) {
            this["maxModels"] = 0;
        }
        if (!("cacheRam" in $$source)) {
            this["cacheRam"] = 0;
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig($$parsedSource as Partial<ServerConfig>);
    }
}

/**
 * ServerLogEntry is one incremental server-log line returned to the frontend:
 * Seq is the line's monotonic ring cursor value, Text the raw line content.
 */
export class ServerLogEntry {
    "seq": number;
    "text": string;

    /** Creates a new ServerLogEntry instance. */
    constructor($$source: Partial<ServerLogEntry> = {}) {
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerLogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerLogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerLogEntry($$parsedSource as Partial<ServerLogEntry>);
    }
}

/**
 * ServerLogsPage bundles one incremental log page: the entries appended since
 * the request cursor plus the next cursor to pass on the following call. It
 * travels as a single struct because the Wails v2 bridge only forwards a
 * bound method's first non-error return value — a second, non-error return
 * would be silently dropped.
 */
export class ServerLogsPage {
    "entries": ServerLogEntry[];
    "next": number;

    /** Creates a new ServerLogsPage instance. */
    constructor($$source: Partial<ServerLogsPage> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("next" in $$source)) {
            this["next"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerLogsPage instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerLogsPage {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new ServerLogsPage($$parsedSource as Partial<ServerLogsPage>);
    }
}

export class SystemInfo {
    "os": string;
    "arch": string;
    "cpu": CPUInfo;
    "memory": MemoryInfo;
    "gpu": GPUInfo[];
    "cuda": CUDAInfo;
    "llamaCpp": LlamaCppInfo;
    "disk"?: DiskUsage | null;

    /** Creates a new SystemInfo instance. */
    constructor($$source: Partial<SystemInfo> = {}) {
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("cpu" in $$source)) {
            this["cpu"] = (new CPUInfo());
        }
        if (!("memory" in $$source)) {
            this["memory"] = (new MemoryInfo());
        }
        if (!("gpu" in $$source)) {
            this["gpu"] = [];
        }
        if (!("cuda" in $$source)) {
            this["cuda"] = (new CUDAInfo());
        }
        if (!("llamaCpp" in $$source)) {
            this["llamaCpp"] = (new LlamaCppInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemInfo {
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType10;
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType13;
        const $$createField6_0 = $$createType14;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cpu" in $$parsedSource) {
            $$parsedSource["cpu"] = $$createField2_0($$parsedSource["cpu"]);
        }
        if ("memory" in $$parsedSource) {
            $$parsedSource["memory"] = $$createField3_0($$parsedSource["memory"]);
        }
        if ("gpu" in $$parsedSource) {
            $$parsedSource["gpu"] = $$createField4_0($$parsedSource["gpu"]);
        }
        if ("cuda" in $$parsedSource) {
            $$parsedSource["cuda"] = $$createField5_0($$parsedSource["cuda"]);
        }
        if ("llamaCpp" in $$parsedSource) {
            $$parsedSource["llamaCpp"] = $$createField6_0($$parsedSource["llamaCpp"]);
        }
        if ("disk" in $$parsedSource) {
            $$parsedSource["disk"] = $$createField7_0($$parsedSource["disk"]);
        }
        return new SystemInfo($$parsedSource as Partial<SystemInfo>);
    }
}

/**
 * UpdateCheckResult is the update-check result returned to the frontend to
 * decide whether a new version exists.
 */
export class UpdateCheckResult {
    "hasUpdate": boolean;

    /**
     * latest version (tag name, e.g. v0.1.1)
     */
    "version": string;

    /**
     * release notes
     */
    "notes": string;

    /**
     * publish time
     */
    "published": string;

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("published" in $$source)) {
            this["published"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}

/**
 * updateDownloadState tracks the progress of the app update download
 * (updating the exe). State machine values: idle / downloading / installing /
 * done / error; "installing" means the downloaded setup installer has been
 * launched and the app is about to exit (installUpdateNow).
 */
export class UpdateDownloadState {
    "status": string;
    "progress": number;
    "total": number;
    "downloaded": number;
    "version": string;
    "filePath": string;
    "error": string;

    /**
     * install kind of the running app: setup (NSIS install) / portable
     */
    "kind": string;

    /**
     * Installer reports whether the downloaded artifact is the setup
     * installer (a portable install may fall back to the installer asset);
     * only installer artifacts support the install-now flow.
     */
    "installer": boolean;

    /** Creates a new UpdateDownloadState instance. */
    constructor($$source: Partial<UpdateDownloadState> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("installer" in $$source)) {
            this["installer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateDownloadState instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateDownloadState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateDownloadState($$parsedSource as Partial<UpdateDownloadState>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = HFFile.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = MonitorGPU.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = DiskUsage.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = ServerLogEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = CPUInfo.createFrom;
const $$createType10 = MemoryInfo.createFrom;
const $$createType11 = GPUInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = CUDAInfo.createFrom;
const $$createType14 = LlamaCppInfo.createFrom;
