// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseLlamaCppDir() {
  return window['go']['main']['App']['BrowseLlamaCppDir']();
}

export function CancelDownloadTask(arg1) {
  return window['go']['main']['App']['CancelDownloadTask'](arg1);
}

export function GetCPU() {
  return window['go']['main']['App']['GetCPU']();
}

export function GetCUDA() {
  return window['go']['main']['App']['GetCUDA']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadTasks() {
  return window['go']['main']['App']['GetDownloadTasks']();
}

export function GetGPU() {
  return window['go']['main']['App']['GetGPU']();
}

export function GetLlamaCpp() {
  return window['go']['main']['App']['GetLlamaCpp']();
}

export function GetLlamaCppDownloadStatus() {
  return window['go']['main']['App']['GetLlamaCppDownloadStatus']();
}

export function GetMemory() {
  return window['go']['main']['App']['GetMemory']();
}

export function GetModelConfig(arg1) {
  return window['go']['main']['App']['GetModelConfig'](arg1);
}

export function GetModelFiles(arg1) {
  return window['go']['main']['App']['GetModelFiles'](arg1);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function PauseDownloadTask(arg1) {
  return window['go']['main']['App']['PauseDownloadTask'](arg1);
}

export function PauseLlamaCppDownload() {
  return window['go']['main']['App']['PauseLlamaCppDownload']();
}

export function RefreshModels() {
  return window['go']['main']['App']['RefreshModels']();
}

export function ResumeDownloadTask(arg1) {
  return window['go']['main']['App']['ResumeDownloadTask'](arg1);
}

export function ResumeLlamaCppDownload() {
  return window['go']['main']['App']['ResumeLlamaCppDownload']();
}

export function SaveModelConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveModelConfig'](arg1, arg2);
}

export function SaveServerConfig(arg1) {
  return window['go']['main']['App']['SaveServerConfig'](arg1);
}

export function SearchDownloads(arg1, arg2) {
  return window['go']['main']['App']['SearchDownloads'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartDownload(arg1, arg2) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2);
}

export function StartLlamaCppDownload() {
  return window['go']['main']['App']['StartLlamaCppDownload']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopLlamaCppDownload() {
  return window['go']['main']['App']['StopLlamaCppDownload']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
