// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseLlamaCppDir():Promise<string>;

export function CancelDownloadTask(arg1:string):Promise<void>;

export function GetCPU():Promise<main.CPUInfo>;

export function GetCUDA():Promise<main.CUDAInfo>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDownloadTasks():Promise<Array<main.DlTask>>;

export function GetGPU():Promise<Array<main.GPUInfo>>;

export function GetLlamaCpp():Promise<main.LlamaCppInfo>;

export function GetLlamaCppDownloadStatus():Promise<main.DownloadState>;

export function GetMemory():Promise<main.MemoryInfo>;

export function GetModelConfig(arg1:string):Promise<main.ModelConfig>;

export function GetModelFiles(arg1:string):Promise<Array<main.HFFileOut>>;

export function GetModels():Promise<Array<main.ModelInfo>>;

export function GetOS():Promise<Record<string, string>>;

export function GetServerConfig():Promise<main.ServerConfig>;

export function GetServerStatus():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function PauseDownloadTask(arg1:string):Promise<void>;

export function PauseLlamaCppDownload():Promise<void>;

export function RefreshModels():Promise<Array<main.ModelInfo>>;

export function ResumeDownloadTask(arg1:string):Promise<void>;

export function ResumeLlamaCppDownload():Promise<void>;

export function SaveModelConfig(arg1:string,arg2:main.ModelConfig):Promise<void>;

export function SaveServerConfig(arg1:main.ServerConfig):Promise<void>;

export function SearchDownloads(arg1:string,arg2:string):Promise<Array<main.HFSearchResult>>;

export function SetTheme(arg1:string):Promise<void>;

export function StartDownload(arg1:string,arg2:Array<string>):Promise<void>;

export function StartLlamaCppDownload():Promise<void>;

export function StartServer():Promise<void>;

export function StopLlamaCppDownload():Promise<void>;

export function StopServer():Promise<void>;
